
package dao;

import model.Patient;
import model.PatientInsurance;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class PatientDao {

    // method to add a patient — patientID is auto-generated by the DB trigger
    // returns the generated PAT-#### id, or null on failure
    public String addPatient(Patient patientObj){
       try{
           String sql = "INSERT INTO patient (fullName,age,gender,diagnosis,consultationFee,registrationDate) VALUES (?,?,?,?,?,?)";
           Connection con = DBConnection.getConnection();
           PreparedStatement pst = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, patientObj.getFullName());
           pst.setInt(2, patientObj.getAge());
           pst.setString(3, patientObj.getGender());
           pst.setString(4, patientObj.getDiagnosis());
           pst.setDouble(5, patientObj.getConsultationFee());
           pst.setDate(6, Date.valueOf(patientObj.getRegistrationDate()));
           pst.executeUpdate();

           // read back the generated patientID
           ResultSet rs = pst.getGeneratedKeys();
           String generatedId = null;
           if (rs.next()) {
               generatedId = rs.getString(1);
           }
           con.close();
           return generatedId;
       } catch(Exception ex){
           ex.printStackTrace();
       }
       return null;
    }
    
    // method to update client informations 
    public int updateClient(Patient patientObj){
        String sql = "UPDATE patient set fullName=?,age=?,gender=?,diagnosis=?,consultationFee=?,registrationDate=? where patientID=?";
        
    try{
       Connection con = DBConnection.getConnection();
       PreparedStatement pst = con.prepareStatement(sql);
       pst.setString(1,patientObj.getFullName());
       pst.setInt(2,patientObj.getAge());
       pst.setString(3, patientObj.getGender());
       pst.setString(4,patientObj.getDiagnosis());
       pst.setDouble(5,patientObj.getConsultationFee());
       pst.setDate(6,Date.valueOf(patientObj.getRegistrationDate()));
       pst.setString(7,patientObj.getPatientId());
       
       int rowsAffected = pst.executeUpdate();
       con.close();
       return rowsAffected;
       
    }catch(Exception ex){
        ex.printStackTrace();
    }
        
        return 0;
        
    }
    
    // method to delete a client
    public int deletePatient(Patient patientObj){
        String sql = "DELETE FROM patient where patientID = ?";
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,patientObj.getPatientId());
            
            return pst.executeUpdate();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return 0;
        
    }
    
    // method to find a Patient and displays informations 
    public Patient findPatient(String PatientID){
      String sql= "SELECT * FROM patient where PatientID=?";
      Patient patientObj= null;
      try{
          Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         pst.setString(1, PatientID);
         
         ResultSet rs = pst.executeQuery();
         if(rs.next()){
             patientObj = new Patient();
             
             patientObj.setPatientId(rs.getString("PatientID"));
             patientObj.setFullName(rs.getString("fullName"));
             patientObj.setAge(rs.getInt("age"));
             patientObj.setGender(rs.getString("gender"));
             patientObj.setDiagnosis(rs.getString("diagnosis"));
             patientObj.setConsultationFee(rs.getDouble("consultationFee"));
             patientObj.setRegistrationDate(rs.getDate("registrationDate").toLocalDate());
             con.close();
         }
      }catch(Exception ex){
          ex.printStackTrace();
      }
        return patientObj;
        
        
    }
    
    // method to insert patient insurance
    public int addPatientInsurance(PatientInsurance pi) {
        String sql = "INSERT INTO patient_insurance (patientID, companyID, policyNumber, valid) VALUES (?,?,?,?)";
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, pi.getPatientID());
            pst.setInt(2, pi.getCompanyID());
            pst.setString(3, pi.getPolicyNumber());
            pst.setBoolean(4, pi.isValid());
            int rows = pst.executeUpdate();
            con.close();
            return rows;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return 0;
    }

    // method to displays all Patient 
   public List<Patient> allPatient(){
       String sql = "SELECT * FROM Patient";
        List<Patient> patientList = new ArrayList<>();
    try{
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        while(rs.next()){
            Patient patientObj = new Patient();
            patientObj.setPatientId(rs.getString("PatientID"));
            patientObj.setFullName(rs.getString("fullName"));
            patientObj.setAge(rs.getInt("age"));
            patientObj.setGender(rs.getString("gender"));
            patientObj.setDiagnosis(rs.getString("diagnosis"));
            patientObj.setConsultationFee(rs.getDouble("consultationFee"));
            patientObj.setRegistrationDate(rs.getDate("registrationDate").toLocalDate());
             
            patientList.add(patientObj);
        }
        con.close();
        return patientList;
    }catch(Exception ex){
        ex.printStackTrace();
    }
        return null;
    
}

    // returns patients joined with their insurance info (LEFT JOIN so uninsured patients still appear)
    public List<Object[]> allPatientsWithInsurance() {
        String sql = "SELECT p.patientID, p.fullName, p.age, p.gender, p.diagnosis, p.consultationFee, p.registrationDate, "
                   + "ic.companyName, pi.policyNumber, pi.valid "
                   + "FROM patient p "
                   + "LEFT JOIN patient_insurance pi ON p.patientID = pi.patientID "
                   + "LEFT JOIN insurance_company ic ON pi.companyID = ic.companyID";
        List<Object[]> rows = new ArrayList<>();
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                int age = rs.getInt("age");
                double fee = rs.getDouble("consultationFee");
                double originalFee = reverseDiscount(age, fee);
                rows.add(new Object[]{
                    rs.getString("patientID"),
                    rs.getString("fullName"),
                    age,
                    rs.getString("gender"),
                    rs.getString("diagnosis"),
                    String.format("%.2f", originalFee) + " → " + String.format("%.2f", fee),
                    rs.getDate("registrationDate") != null ? rs.getDate("registrationDate").toLocalDate().toString() : "",
                    rs.getString("companyName") != null ? rs.getString("companyName") : "None",
                    rs.getString("policyNumber") != null ? rs.getString("policyNumber") : "-",
                    rs.getObject("valid") != null ? (rs.getBoolean("valid") ? "Yes" : "No") : "-"
                });
            }
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return rows;
    }

    // reverse the discount to recover the original fee for display
    private double reverseDiscount(int age, double discountedFee) {
        if (age < 12)  return discountedFee / 0.50;
        if (age > 60)  return discountedFee / 0.70;
        return discountedFee;
    }
}