/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.InsuranceCompanyDao;
import dao.PatientDao;
import model.InsuranceCompany;
import model.Patient;
import model.PatientInsurance;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shema
 */
public class App extends javax.swing.JFrame {

    PatientDao patientDao = new PatientDao();
    InsuranceCompanyDao insuranceDao = new InsuranceCompanyDao();
    private String selectedPatientId = null;

    public App() {
        initComponents();
        loadInsuranceCombo();
        refreshPatientsTable();
        refreshInsuranceTable();

        // mutual exclusion for valid/invalid checkboxes
        insuranceValid.addActionListener(e -> { if (insuranceValid.isSelected()) insuranceInvalid.setSelected(false); });
        insuranceInvalid.addActionListener(e -> { if (insuranceInvalid.isSelected()) insuranceValid.setSelected(false); });

        patientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = patientsTable.getSelectedRow();
                if (row == -1) return;
                selectedPatientId = patientsTable.getValueAt(row, 0).toString();
                fullNamesTxt.setText(patientsTable.getValueAt(row, 1).toString());
                ageTxt.setText(patientsTable.getValueAt(row, 2).toString());
                genderTxt.setSelectedItem(patientsTable.getValueAt(row, 3).toString());
                ageTxt1.setText(patientsTable.getValueAt(row, 4).toString());
                consultationFeeTxt.setText(patientsTable.getValueAt(row, 5).toString());
                // fill insurance fields
                String companyName = patientsTable.getValueAt(row, 7).toString();
                policyNumber.setText(patientsTable.getValueAt(row, 8).toString());
                String valid = patientsTable.getValueAt(row, 9).toString();
                insuranceValid.setSelected("Yes".equals(valid));
                insuranceInvalid.setSelected("No".equals(valid));
                for (int i = 0; i < patientInsuranceCompany.getItemCount(); i++) {
                    if (patientInsuranceCompany.getItemAt(i).equals(companyName)) {
                        patientInsuranceCompany.setSelectedIndex(i);
                        break;
                    }
                }
            }
        });
    }

    private void loadInsuranceCombo() {
        patientInsuranceCompany.removeAllItems();
        patientInsuranceCompany.addItem("-- None --");
        for (InsuranceCompany ic : insuranceDao.findAllCompanies()) {
            patientInsuranceCompany.addItem(ic.getCompanyName());
        }
    }

    private void refreshPatientsTable() {
        DefaultTableModel model = (DefaultTableModel) patientsTable.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{
            "Patient ID", "Full Name", "Age", "Gender", "Diagnosis",
            "Consultation Fee", "Registration Date", "Insurance Company", "Policy Number", "Valid"
        });
        for (Object[] row : patientDao.allPatientsWithInsurance()) {
            model.addRow(row);
        }
    }

    private void refreshInsuranceTable() {
        List<InsuranceCompany> list = insuranceDao.findAllCompanies();
        DefaultTableModel model = (DefaultTableModel) companiesTable.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Company ID", "Company Name", "Coverage %", "Phone", "Email"});
        if (list == null) return;
        for (InsuranceCompany ic : list) {
            model.addRow(new Object[]{
                ic.getCompanyID(), ic.getCompanyName(), ic.getCoveragePercentage(),
                ic.getContactPhone(), ic.getContactEmail()
            });
        }
    }

    private void clearPatientFields() {
        fullNamesTxt.setText("");
        ageTxt.setText("");
        ageTxt1.setText("");
        consultationFeeTxt.setText("");
        policyNumber.setText("");
        genderTxt.setSelectedIndex(0);
        patientInsuranceCompany.setSelectedIndex(0);
        insuranceValid.setSelected(false);
        insuranceInvalid.setSelected(false);
        selectedPatientId = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        tabsPane = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fullNamesTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageTxt1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        consultationFeeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addPatientButton = new javax.swing.JButton();
        updatePatientButton = new javax.swing.JButton();
        deletePatientButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        patientInsuranceCompany = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        policyNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        insuranceValid = new javax.swing.JCheckBox();
        insuranceInvalid = new javax.swing.JCheckBox();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        companiesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        companyNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        coveragePercentageTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phoneCompanyTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailCompanyTxt = new javax.swing.JTextField();
        updateCompanyBtn = new javax.swing.JButton();
        deleteCompanyBtn = new javax.swing.JButton();
        saveCompanyBtn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 37, 41));

        container.setBackground(new java.awt.Color(33, 37, 41));

        tabsPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        patientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(patientsTable);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));

        jLabel1.setBackground(new java.awt.Color(33, 37, 41));
        jLabel1.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 193, 7));
        jLabel1.setText("ADD NEW PATIENT");

        fullNamesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNamesTxtActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 193, 7));
        jLabel2.setText("FULL NAMES");

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 193, 7));
        jLabel3.setText("AGE");

        ageTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxt1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 193, 7));
        jLabel4.setText("GENDER");

        genderTxt.setBackground(new java.awt.Color(255, 255, 255));
        genderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderTxt.setToolTipText("");
        genderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTxtActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 193, 7));
        jLabel5.setText("DIAGNOSIS");

        consultationFeeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationFeeTxtActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 193, 7));
        jLabel6.setText("CONSULTATION FEE");

        addPatientButton.setBackground(new java.awt.Color(255, 193, 7));
        addPatientButton.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        addPatientButton.setForeground(new java.awt.Color(33, 37, 41));
        addPatientButton.setText("SAVE PATIENT");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        updatePatientButton.setBackground(new java.awt.Color(255, 193, 7));
        updatePatientButton.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        updatePatientButton.setForeground(new java.awt.Color(33, 37, 41));
        updatePatientButton.setText("UPDATE PATIENT");
        updatePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientButtonActionPerformed(evt);
            }
        });

        deletePatientButton.setBackground(new java.awt.Color(255, 193, 7));
        deletePatientButton.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        deletePatientButton.setForeground(new java.awt.Color(33, 37, 41));
        deletePatientButton.setText("DELETE PATIENT");
        deletePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientButtonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 102, 204));
        jLabel13.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 193, 7));
        jLabel13.setText("INSURANCE COMPANY");

        patientInsuranceCompany.setBackground(new java.awt.Color(255, 255, 255));
        patientInsuranceCompany.setToolTipText("");
        patientInsuranceCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientInsuranceCompanyActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 102, 204));
        jLabel14.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 193, 7));
        jLabel14.setText("INSURANCE VALIDITY");

        policyNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyNumberActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 102, 204));
        jLabel15.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 193, 7));
        jLabel15.setText("POLICY NUMBER");

        insuranceValid.setFont(new java.awt.Font("Ubuntu Sans", 1, 12)); // NOI18N
        insuranceValid.setForeground(new java.awt.Color(255, 255, 255));
        insuranceValid.setText("VALID");
        insuranceValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceValidActionPerformed(evt);
            }
        });

        insuranceInvalid.setFont(new java.awt.Font("Ubuntu Sans", 1, 12)); // NOI18N
        insuranceInvalid.setForeground(new java.awt.Color(255, 255, 255));
        insuranceInvalid.setText("INVALID");
        insuranceInvalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceInvalidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(insuranceValid)
                                .addGap(54, 54, 54)
                                .addComponent(insuranceInvalid))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(ageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(fullNamesTxt)
                                .addComponent(genderTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consultationFeeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(patientInsuranceCompany, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(policyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(updatePatientButton)
                            .addGap(18, 18, 18)
                            .addComponent(addPatientButton)
                            .addGap(18, 18, 18)
                            .addComponent(deletePatientButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(301, 301, 301)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fullNamesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultationFeeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(patientInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(insuranceValid)
                    .addComponent(insuranceInvalid))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePatientButton)
                    .addComponent(addPatientButton)
                    .addComponent(deletePatientButton))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        tabsPane.addTab("PATIENTS", jSplitPane1);

        companiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(companiesTable);

        jSplitPane2.setLeftComponent(jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));

        jLabel8.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 193, 7));
        jLabel8.setText("COMPANY MANAGEMENT");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 193, 7));
        jLabel9.setText("NAME");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 193, 7));
        jLabel10.setText("COVERAGE PERCENTAGE");

        coveragePercentageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coveragePercentageTxtActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 193, 7));
        jLabel11.setText("CONTACT PHONE");

        phoneCompanyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCompanyTxtActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 193, 7));
        jLabel12.setText("CONTACT EMAIL");

        emailCompanyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCompanyTxtActionPerformed(evt);
            }
        });

        updateCompanyBtn.setBackground(new java.awt.Color(255, 193, 7));
        updateCompanyBtn.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        updateCompanyBtn.setForeground(new java.awt.Color(33, 37, 41));
        updateCompanyBtn.setText("UPDATE COMPANY");

        deleteCompanyBtn.setBackground(new java.awt.Color(255, 193, 7));
        deleteCompanyBtn.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        deleteCompanyBtn.setForeground(new java.awt.Color(33, 37, 41));
        deleteCompanyBtn.setText("DELETE COMPANY");
        deleteCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompanyBtnActionPerformed(evt);
            }
        });

        saveCompanyBtn2.setBackground(new java.awt.Color(255, 193, 7));
        saveCompanyBtn2.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        saveCompanyBtn2.setForeground(new java.awt.Color(33, 37, 41));
        saveCompanyBtn2.setText("SAVE COMPANY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(updateCompanyBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(saveCompanyBtn2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteCompanyBtn))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(companyNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coveragePercentageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneCompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailCompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(coveragePercentageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneCompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(emailCompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCompanyBtn)
                    .addComponent(deleteCompanyBtn)
                    .addComponent(saveCompanyBtn2))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        tabsPane.addTab("INSURANCE COMPANIES", jSplitPane2);

        jLabel7.setFont(new java.awt.Font("Ubuntu Sans", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 193, 7));
        jLabel7.setText("PATIENT AND INSURANCE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabsPane)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabsPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        String fullName = fullNamesTxt.getText().trim();
        String ageStr   = ageTxt.getText().trim();
        String diagnosis = ageTxt1.getText().trim();
        String gender   = (String) genderTxt.getSelectedItem();
        String feeStr   = consultationFeeTxt.getText().trim();
        String policy   = policyNumber.getText().trim();
        String selectedCompany = (String) patientInsuranceCompany.getSelectedItem();

        if (fullName.isEmpty() || ageStr.isEmpty() || diagnosis.isEmpty() || feeStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }
        int age; double fee;
        try {
            age = Integer.parseInt(ageStr);
            fee = Double.parseDouble(feeStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age and Consultation Fee must be numbers!");
            return;
        }

        Patient p = new Patient(null, fullName, age, gender, diagnosis, fee, LocalDate.now());
        String generatedId = patientDao.addPatient(p);
        if (generatedId != null) {
            // insert insurance if a company and policy number are provided
            if (selectedCompany != null && !selectedCompany.equals("-- None --") && !policy.isEmpty()) {
                InsuranceCompany ic = insuranceDao.findAllCompanies().stream()
                    .filter(c -> c.getCompanyName().equals(selectedCompany)).findFirst().orElse(null);
                if (ic != null) {
                    PatientInsurance pi = new PatientInsurance();
                    pi.setPatientID(generatedId);
                    pi.setCompanyID(ic.getCompanyID());
                    pi.setPolicyNumber(policy);
                    pi.setValid(insuranceValid.isSelected());
                    patientDao.addPatientInsurance(pi);
                }
            }
            JOptionPane.showMessageDialog(this, "Patient saved successfully!");
            refreshPatientsTable();
            clearPatientFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save patient.");
        }
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void consultationFeeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationFeeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultationFeeTxtActionPerformed

    private void genderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTxtActionPerformed

    private void ageTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxt1ActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void fullNamesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNamesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNamesTxtActionPerformed

    private void coveragePercentageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coveragePercentageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coveragePercentageTxtActionPerformed

    private void phoneCompanyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCompanyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneCompanyTxtActionPerformed

    private void emailCompanyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCompanyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCompanyTxtActionPerformed

    private void updatePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientButtonActionPerformed
        if (selectedPatientId == null) {
            JOptionPane.showMessageDialog(this, "Select a patient from the table first.");
            return;
        }
        String fullName  = fullNamesTxt.getText().trim();
        String ageStr    = ageTxt.getText().trim();
        String diagnosis = ageTxt1.getText().trim();
        String gender    = (String) genderTxt.getSelectedItem();
        String feeStr    = consultationFeeTxt.getText().trim();
        if (fullName.isEmpty() || ageStr.isEmpty() || diagnosis.isEmpty() || feeStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }
        try {
            int row = patientsTable.getSelectedRow();
            LocalDate regDate = LocalDate.parse(patientsTable.getValueAt(row, 6).toString());
            Patient p = new Patient(selectedPatientId, fullName, Integer.parseInt(ageStr),
                gender, diagnosis, Double.parseDouble(feeStr), regDate);
            if (patientDao.updateClient(p) > 0) {
                JOptionPane.showMessageDialog(this, "Patient updated successfully!");
                refreshPatientsTable();
                clearPatientFields();
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age and Consultation Fee must be numbers!");
        }
    }//GEN-LAST:event_updatePatientButtonActionPerformed

    private void deletePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientButtonActionPerformed
        if (selectedPatientId == null) {
            JOptionPane.showMessageDialog(this, "Select a patient from the table first.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete patient " + selectedPatientId + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Patient p = new Patient();
            p.setPatientId(selectedPatientId);
            if (patientDao.deletePatient(p) > 0) {
                JOptionPane.showMessageDialog(this, "Patient deleted successfully!");
                refreshPatientsTable();
                clearPatientFields();
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed.");
            }
        }
    }//GEN-LAST:event_deletePatientButtonActionPerformed

    private void deleteCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompanyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCompanyBtnActionPerformed

    private void patientInsuranceCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientInsuranceCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientInsuranceCompanyActionPerformed

    private void policyNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policyNumberActionPerformed

    private void insuranceValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceValidActionPerformed

    private void insuranceInvalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceInvalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceInvalidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextField ageTxt1;
    private javax.swing.JTable companiesTable;
    private javax.swing.JTextField companyNameTxt;
    private javax.swing.JTextField consultationFeeTxt;
    private javax.swing.JPanel container;
    private javax.swing.JTextField coveragePercentageTxt;
    private javax.swing.JButton deleteCompanyBtn;
    private javax.swing.JButton deletePatientButton;
    private javax.swing.JTextField emailCompanyTxt;
    private javax.swing.JTextField fullNamesTxt;
    private javax.swing.JComboBox<String> genderTxt;
    private javax.swing.JCheckBox insuranceInvalid;
    private javax.swing.JCheckBox insuranceValid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JComboBox<String> patientInsuranceCompany;
    private javax.swing.JTable patientsTable;
    private javax.swing.JTextField phoneCompanyTxt;
    private javax.swing.JTextField policyNumber;
    private javax.swing.JButton saveCompanyBtn2;
    private javax.swing.JTabbedPane tabsPane;
    private javax.swing.JButton updateCompanyBtn;
    private javax.swing.JButton updatePatientButton;
    // End of variables declaration//GEN-END:variables
}
