/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PatientDao;
import java.time.LocalDate;
import model.Patient;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class updatepatient extends javax.swing.JFrame {

    /**
     * Creates new form registerPatient
     */
    public updatepatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientIdtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        diagnosisTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        consultationTxt = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Documents\\mes phtoto\\jicon.png")); // NOI18N
        jLabel3.setText("jLabel3");

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(309, 309, 309))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE INFO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Patient id ");

        patientIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdtxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("New FULL NAME");

        fullNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("New Age");

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("New Diagnosis");

        diagnosisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisTxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("New Consultation Fee");

        consultationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(patientIdtxt)
                        .addComponent(fullNameTxt)
                        .addComponent(ageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdtxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    String patientID = patientIdtxt.getText().trim(); 
    String fullName = fullNameTxt.getText().trim();
    String gender = genderTxt.getText().trim();
    String diagnosis = diagnosisTxt.getText().trim();
    String ageText = ageTxt.getText().trim();
    String consultationText = consultationTxt.getText().trim();
    
    if(patientID.isEmpty()){
        JOptionPane.showMessageDialog(this,"Patient ID must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
    else if(fullName.isEmpty()){
        JOptionPane.showMessageDialog(this,"Full name must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
    else if(gender.isEmpty()){
        JOptionPane.showMessageDialog(this,"Gender must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
   else if(diagnosis.isEmpty()){
        JOptionPane.showMessageDialog(this,"Diagnosis must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
   else if(consultationText.isEmpty()){
        JOptionPane.showMessageDialog(this,"age must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
    else if(consultationText.isEmpty()){
        JOptionPane.showMessageDialog(this,"consltation must not be empty","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
     }
    
    else{
       int age = 0;
        double consultationFee = 0;
        
        try{
             age = Integer.parseInt(ageText);
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,"Age must be numeric");
            return;
        }
        
        try{
             consultationFee = Double.parseDouble(consultationText);
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,"Consultation Fee must be numeric");
            return;
        }
        
        if(!patientID.matches("^PAT-[0-9]{4}$")){
        JOptionPane.showMessageDialog(this,"Format must be PAT-####","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
    }
        else if(!fullName.matches("^[a-zA-Z ]+$") || fullName.length()<5){
                 JOptionPane.showMessageDialog(this,"full name must have least 5 characters ","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else if(age<0 || age>120){
                 JOptionPane.showMessageDialog(this,"Age should be a number between 0 and 120","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else if(!diagnosis.matches("^[a-zA-Z]+$") ||  diagnosis.length()<5 ){
                 JOptionPane.showMessageDialog(this,"diagnosis must have least 5 characters","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else if (consultationFee<5000 || consultationFee>50000){
                JOptionPane.showMessageDialog(this,"consulstation fee should be a number between 5000 and 50000 ","VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else if(!gender.equalsIgnoreCase("male") && !gender.equalsIgnoreCase("female")){
                JOptionPane.showMessageDialog(this," gender should be male or female"," VALIDATION MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(age<12){
                    double discount = consultationFee * 0.5;
                    consultationFee = consultationFee - discount;
                    JOptionPane.showMessageDialog(this,"discount is "+discount);
                    JOptionPane.showMessageDialog(this," new consultation fee is : "+consultationFee);
                }
                else if(age>60){
                    double discount = consultationFee * 0.3;
                    consultationFee = consultationFee - discount;
                    JOptionPane.showMessageDialog(this,"discount is " +discount);
                    JOptionPane.showMessageDialog(this," new consultation fee is : " +consultationFee);
                }
                else{
                    JOptionPane.showMessageDialog(this," no discount");
                }
            Patient patientObj = new Patient();
            patientObj.setPatientId(patientID);
            patientObj.setFullName(fullName);
            patientObj.setAge(age);
            patientObj.setGender(gender);
            patientObj.setDiagnosis(diagnosis);
            patientObj.setConsultationFee(consultationFee);
            patientObj.setRegistrationDate(LocalDate.now());
            
            // send to the dao 
            PatientDao dao = new PatientDao();
            int rowsAffected = dao.updateClient(patientObj);
            if(rowsAffected > 0){
                JOptionPane.showMessageDialog(this,"UPDATE OF PATIENT INFORMATION IS A SUCCESS");
            }
            else{
                    JOptionPane.showMessageDialog(this,"UPDATE of Patient information Failed");
            }
        }
    }
    
    }//GEN-LAST:event_updateBtnActionPerformed

    private void fullNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void diagnosisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisTxtActionPerformed

    private void consultationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultationTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        patientIdtxt.setText("");
        fullNameTxt.setText("");
        ageTxt.setText("");
        genderTxt.setText("");
        diagnosisTxt.setText("");
        consultationTxt.setText("");
        
        patientIdtxt.requestFocus();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatepatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField consultationTxt;
    private javax.swing.JTextField diagnosisTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patientIdtxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
